on: ["push"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: npm install, make test-coverage
      run: |
        npm install
        npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}